# Generated by Django 4.2.3 on 2023-08-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0003_advertisements_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements',
            name='image',
            field=models.ImageField(default=1, upload_to='advertisments/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
